#ifndef NALUNITTYPE
#define NALUNITTYPE


enum NalUnitType {
    UNSPECIFIED = 0,
    NON_IDR_SLICE_LAYER_WITHOUT_PARTITIONING_RBSP = 1, // VCL - start
    SLICE_DATA_PARTITION_A_LAYER_RBSP = 2,
    SLICE_DATA_PARTITION_B_LAYER_RBSP = 3,
    SLICE_DATA_PARTITION_C_LAYER_RBSP = 4,
    IDR_SLICE_LAYER_WITHOUT_PARTITIONING_RBSP = 5, // VCL - end
    SER_RBSP = 6,
    SEQ_PARAMATER_SET_RBSP = 7,
    PIC_PARAMATER_SET_RBSP = 8,
    ACCESS_UNIT_DELIMITER_RBSP = 9,
    END_OF_SEQUENCE_RBSP = 10,
    END_OF_STREAM_RBSP = 11,
    FILLER_DATA_RBSP = 12,
    RESERVED_13 = 13,
    RESERVED_14 = 14, // NAL unit type 14 is used for prefix NAL unit
    RESERVED_15 = 15, //NAL unit type 15 is used for subset sequence parameter set
    RESERVED_16 = 16,
    RESERVED_17 = 17,
    RESERVED_18 = 18,
    RESERVED_19 = 19,
    RESERVED_20 = 20, // NAL unit type 20 is used for coded slice in scalable extension
    RESERVED_21 = 21,
    RESERVED_22 = 22,
    RESERVED_23 = 23,
    UNSPECIFIED_24 = 24,
    UNSPECIFIED_25 = 24,
    UNSPECIFIED_26 = 24,
    UNSPECIFIED_27 = 24,
    UNSPECIFIED_28 = 24,
    UNSPECIFIED_29 = 24,
    UNSPECIFIED_30 = 24,
    UNSPECIFIED_31 = 24
};

#endif // NALUNITTYPE

